defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:12

version: 2.1
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - run: npm run lint -- --fix
      - run: npm run sort
      - run:
          name: commit auto fixes
          command: |
            if [ "$(git diff --quiet && echo 0 || echo $?)" -gt 0 ]; then
              git config --global user.email $(git show -s --format=%ae)
              git config --global user.name $(git show -s --format=%an)
              git commit -am "Autofix"
              git push -u origin ${CIRCLE_BRANCH}
              circleci step halt
            fi
      - run: npm t
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  release:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set user
          command: |
            git config --global user.name a1vy
            git config --global user.email a01101100vy@gmail.com
      - run:
          name: Clone docs and clean everything
          command: |
            git clone -b gh-pages --single-branch $CIRCLE_REPOSITORY_URL docs
            cd docs
            ls -a | grep -v .git | grep -v .circleci | egrep -vU "\.$" | xargs rm -rf
            cd -
      - run: npm run build
      - run:
          name: Check for changes and commit
          command: |
            cd docs
            git diff --exit-code && circleci step halt
            git add .
            git commit -m "$(curl -s whatthecommit.com/index.txt)"
            git push origin master --force-with-lease
            cd -
      - run:
          name: CloufFlare - Purge everything
          command: |
            curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
             -H "X-Auth-Email: ${CF_EMAIL}" \
             -H "X-Auth-Key: ${CF_API_KEY}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
workflows:
  version: 2.1
  integration:
    jobs:
      - tests:
          context: globalenv
      - release:
          context: globalenv
          requires:
            - tests
          filters:
            branches:
              only:
                - build
