version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    steps:
      - run:
          name: CloufFlare - Purge everything
          command: |
            curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
             -H "X-Auth-Email: ${CF_EMAIL}" \
             -H "X-Auth-Key: ${CF_API_KEY}" \
             -H "Content-Type: application/json" \
             --data '{"purge_everything":true}'
workflows:
  version: 2
  release:
    jobs:
      - build:
          context: globalenv
          filters:
            branches:
              only:
                - gh-pages
